# Generated by Django 3.2.6 on 2021-09-08 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('all_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.normaluserprofile')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vipuserprofile')),
            ],
        ),
    ]
