# Generated by Django 3.2.6 on 2021-09-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('users', '0001_initial'),
        ('cart_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_p',
            field=models.ForeignKey(default='61e21fecd0c145afa2061301d81d05e9', on_delete=django.db.models.deletion.CASCADE, to='users.normaluserprofile'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='cart_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cartinf', to='cart_ordering.cart'),
        ),
        migrations.AddField(
            model_name='ordering',
            name='product_ID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='product.productbase'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_status',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('id', 'user_p')},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='all_price',
        ),
    ]
