# Generated by Django 3.2.6 on 2021-09-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210906_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluserprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='normaluserprofile',
            name='last_name',
        ),
    ]
