# Generated by Django 3.2.6 on 2021-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210906_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluserprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
