# Generated by Django 3.2.6 on 2021-09-03 15:33

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210902_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='name',
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to=product.models.model_image_directory_path),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='product.productbase'),
        ),
    ]
