# Generated by Django 3.2.6 on 2021-09-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210903_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='ImageProduct\\<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
