# Generated by Django 3.2.6 on 2021-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_imageproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='ImageProduct/<django.db.models.fields.CharField>'),
        ),
    ]
